#!/usr/bin/env python3
"""Generate the conversion reference and registry-wide contract test."""

from pathlib import Path
import re


ROOT = Path(__file__).resolve().parents[1]
HEADER = ROOT / "src" / "ESPressio_UnitConversions.hpp"
DOC = ROOT / "docs" / "UNIT_CONVERSIONS.md"
TEST = ROOT / "tests" / "test_conversions.cpp"


def registrations(source, structure):
    pattern = re.compile(
        r"struct " + structure + r"<\s*(.*?)\s*>\s*(?::[^\{]+)?\{",
        re.DOTALL,
    )
    return [
        re.findall(r"UnitContext::(\w+)", match.group(1))
        for match in pattern.finditer(source)
    ]


source = HEADER.read_text(encoding="utf-8")
formulas = registrations(source, "UnitFormula")
direct = registrations(source, "IsDirectUnitContextConversion")
contexts = sorted(
    path.stem.removeprefix("ESPressio_")
    for path in (ROOT / "src").glob("ESPressio_*.hpp")
    if re.search(r"struct \w+ : public Unit<", path.read_text(encoding="utf-8"))
)

direct_by_source = {context: [] for context in contexts}
formula_by_target = {context: [] for context in contexts}
for source_context, target_context in direct:
    direct_by_source[source_context].append(target_context)
for target_context, *source_contexts in formulas:
    formula_by_target[target_context].append(source_contexts)

doc = [
    "# Unit Conversion Reference",
    "",
    "This file is generated by `tools/generate_conversion_assets.py`. Do not edit it directly.",
    "",
    "Every argument to `From(...)` must be a specialized ESPressio unit type. Raw numeric arguments and unregistered context combinations are rejected at compile time. Input values are normalized to their context's canonical magnitude before a formula is evaluated with `long double` precision; the result is range-checked and stored at the target type's canonical magnitude.",
    "",
    "Equivalent contexts use `source.ToContext<Target, TResult>()`. Calculated contexts use `Target<TResult>::From(inputs...)`.",
    "",
]
for context in contexts:
    doc += [f"## `{context}`", ""]
    targets = sorted(direct_by_source[context])
    doc.append("Direct targets: " + (
        ", ".join(f"`{target}`" for target in targets) if targets else "None."
    ))
    doc.append("")
    signatures = formula_by_target[context]
    if signatures:
        doc.append("Supported factories:")
        doc.append("")
        for inputs in signatures:
            arguments = ", ".join(f"const {item}<T>&" for item in inputs)
            doc.append(f"- `{context}<TResult>::From({arguments})`")
    else:
        doc.append("Supported factories: None.")
    doc.append("")
DOC.parent.mkdir(exist_ok=True)
DOC.write_text("\n".join(doc) + "\n", encoding="utf-8")

test = [
    "// Generated by tools/generate_conversion_assets.py. Do not edit.",
    '#include "ESPressio_Units.hpp"',
    "",
    "#include <cmath>",
    "#include <iostream>",
    "#include <type_traits>",
    "#include <utility>",
    "",
    "using namespace ESPressio::Units;",
    "",
    "template <typename...> struct MakeVoid { typedef void type; };",
    "template <typename... T> using VoidT = typename MakeVoid<T...>::type;",
    "",
    "template <typename TTarget, typename TEnable, typename... TInputs>",
    "struct CanCreateFromImplementation : std::false_type { };",
    "",
    "template <typename TTarget, typename... TInputs>",
    "struct CanCreateFromImplementation<TTarget, VoidT<decltype(",
    "    TTarget::From(std::declval<const TInputs&>()...)",
    ")>, TInputs...> : std::true_type { };",
    "",
    "template <typename TTarget, typename... TInputs>",
    "struct CanCreateFrom : CanCreateFromImplementation<",
    "    TTarget, void, TInputs...",
    "> { };",
    "",
    "int main() {",
    "    unsigned checks = 0;",
]
for target, *inputs in formulas:
    args = ", ".join(f"{item}<double>(2.0)" for item in inputs)
    type_args = ", ".join(f"{item}<double>" for item in inputs)
    test += [
        f"    static_assert(CanCreateFrom<{target}<double>, {type_args}>::value,",
        f'        "Registered {target} formula must be callable");',
        "    {",
        f"        const {target}<double> result = {target}<double>::From({args});",
        "        if (!std::isfinite(result.value) ||",
        f"            result.orderOfMagnitude != {target}<double>::baseOrderOfMagnitude) {{",
        f'            std::cerr << "Failed {target} factory contract\\n";',
        "            return 1;",
        "        }",
        "        ++checks;",
        "    }",
    ]
for source_context, target_context in direct:
    test += [
        "    {",
        f"        const {target_context}<double> result = {source_context}<double>(2.0).ToContext<{target_context}, double>();",
        "        if (result.value != 2.0 ||",
        f"            result.orderOfMagnitude != {target_context}<double>::baseOrderOfMagnitude) {{",
        f'            std::cerr << "Failed {source_context} to {target_context} direct conversion\\n";',
        "            return 1;",
        "        }",
        "        ++checks;",
        "    }",
    ]
test += [
    "    static_assert(!CanCreateFrom<Velocity<double>, double, Time<double>>::value,",
    '        "Raw numeric inputs must be rejected");',
    "    static_assert(!CanCreateFrom<Velocity<double>, Mass<double>, Time<double>>::value,",
    '        "Dimensionally invalid unit inputs must be rejected");',
    "",
    "    const Velocity<double> normalized = Velocity<double>::From(",
    "        Distance<double>(100.0, Base),",
    "        Time<double>(500.0, Milli)",
    "    );",
    "    if (std::fabs(normalized.value - 200.0) > 1.0e-12) {",
    '        std::cerr << "Magnitude normalization failed\\n";',
    "        return 1;",
    "    }",
    "    ++checks;",
    "",
    "    const Velocity<double> predefinedMagnitudeInput =",
    "        Velocity<double>::From(",
    "            Distance<double>(100.0), MilliSeconds<double>(500.0)",
    "        );",
    "    if (std::fabs(predefinedMagnitudeInput.value - 200.0) > 1.0e-12) {",
    '        std::cerr << "Predefined time input normalization failed\\n";',
    "        return 1;",
    "    }",
    "    ++checks;",
    "",
    "    const MilliSeconds<double> predefinedMagnitudeResult =",
    "        MilliSeconds<double>::From(Frequency<double>(2.0));",
    "    if (std::fabs(predefinedMagnitudeResult.value - 500.0) > 1.0e-12 ||",
    "        predefinedMagnitudeResult.orderOfMagnitude != Milli) {",
    '        std::cerr << "Predefined time result scaling failed\\n";',
    "        return 1;",
    "    }",
    "    ++checks;",
    "",
    "    const Velocity<int> rounded = Velocity<int>::From(",
    "        Distance<double>(5.0), Time<double>(2.0)",
    "    );",
    "    if (rounded.value != 3) {",
    '        std::cerr << "Integral formula result was not rounded\\n";',
    "        return 1;",
    "    }",
    "    ++checks;",
    "",
    "    bool overflowRejected = false;",
    "    try {",
    "        (void) Velocity<signed char>::From(",
    "            Distance<double>(1000.0), Time<double>(1.0)",
    "        );",
    "    } catch (const std::overflow_error&) {",
    "        overflowRejected = true;",
    "    }",
    "    if (!overflowRejected) {",
    '        std::cerr << "Out-of-range formula result was not rejected\\n";',
    "        return 1;",
    "    }",
    "    ++checks;",
    "",
    "    const int uncheckedMagnitude =",
    "        Distance<int>(1, Mega).ToMagnitudeUnchecked<int>(Kilo);",
    "    if (uncheckedMagnitude != 1000) {",
    '        std::cerr << "Unchecked magnitude conversion failed\\n";',
    "        return 1;",
    "    }",
    "    ++checks;",
    "",
    "    const Velocity<int> uncheckedFormula =",
    "        Velocity<int>::FromUnchecked(",
    "            Distance<double>(5.0), Time<double>(2.0)",
    "        );",
    "    if (uncheckedFormula.value != 3) {",
    '        std::cerr << "Unchecked formula conversion failed\\n";',
    "        return 1;",
    "    }",
    "    ++checks;",
    "",
    "    bool divisionByZeroRejected = false;",
    "    try {",
    "        (void) Velocity<double>::From(Distance<double>(1.0), Time<double>(0.0));",
    "    } catch (const std::domain_error&) {",
    "        divisionByZeroRejected = true;",
    "    }",
    "    if (!divisionByZeroRejected) {",
    '        std::cerr << "Zero denominator was not rejected\\n";',
    "        return 1;",
    "    }",
    "    ++checks;",
    "",
    '    std::cout << "Passed " << checks',
    '              << " generated conversion checks across "',
    f'              << {len(formulas)} << " formulas and "',
    f'              << {len(direct)} << " direct conversions.\\n";',
    "    return 0;",
    "}",
]
TEST.write_text("\n".join(test) + "\n", encoding="utf-8")

print(
    f"Generated {len(formulas)} formulas and {len(direct)} direct conversions "
    f"for {len(contexts)} unit types."
)
